package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"

	"github.com/Lucas-Linhar3s/go-graphql-api/graph/model"
	"github.com/google/uuid"
)

// Persons is the resolver for the persons field.
func (r *queryResolver) Persons(ctx context.Context) ([]*model.Person, error) {
	var persons []*model.Person
	person := model.Person{
		ID:     uuid.NewString(),
		Name:   "Lucas",
		Age:    23,
		IsMale: true,
	}

	for i := 0; i < 3; i++ {
		persons = append(persons, &person)
	}

	return persons, nil

	// panic(fmt.Errorf("not implemented: Persons - persons"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
